### ISSUE TITLE
About the obara saika integral method

### ISSUE THREAD

**Issue by mavenlin** [Walter-Feng/Hartree-Fock-in-CPP#3]
While the implementation of `overlap` and `nuclear_attration` integrals are following the recursive relations in the original 1985 paper, the implementation of `kinetic` and `electron_repulsion` integrals seem not to be exactly aligned. i.e. instead of computing recursively, they are both expanded into summing over all the pairs.

Does this implementation lead to fewer FLOPS compared to the original RR? Is there any reference that derives this alternative form?

BTW, it is mentioned [here](https://github.com/Walter-Feng/Hartree-Fock-in-CPP/blob/main/src/integral/obara_saika.cpp#L65) that the implementation has some error, has this been fixed?

**Comment by Walter-Feng** [comment]
It's more like *My* historical reason for learning & writing Hartree-Fock. The Obara-Saika part is inherited from my C version of Hartree-Fock, and it was written when I was being an RA in University of Bristol, and thus the thesis mentioned in the comments, instead of directly implementing the Obara-Saika scheme.

So it is relatively unrelated to the performance - the codes should be slower and ill-optimized. To implement a faster one, maybe the first step is to parse RRs before runtime, or simply use good libraries. This repo is more intended for tutorials, so I believe less-optimized code can promote better understanding.

The implementation is not fixed yet- I was thinking I have correct implemention in Rys quadrature method, maybe not a hurry for me to fix the ERI in Obara-Saika. Maybe it's good chance I give it a look and probably directly implement the OS scheme.

**Comment by Walter-Feng** [comment]
But overall it will require less computation to sum over all the function pairs, as these pairs can be utilized for both sides of the integrals (which I didn't do in my code).

By the way, the thesis I was referencing has some errors. I recall it was \xi -> \zeta in ERI, if you really want to check it.

**Comment by mavenlin** [comment]
Thanks for the clarification!

**Comment by Walter-Feng** [comment]
Obara-Saika scheme of ERI is now correctly implemented. Super slow though :(
